apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: yorkie
        metrics_path: /metrics
        scrape_interval: 5s
        static_configs:
        - targets:
          - yorkie-service:11102
