apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: default
  labels:
    app: envoy
spec:
  clusterIP: None
  selector:
    app: envoy
  ports:
    - name: web-sdk-port
      port: 8080
      targetPort: 8080
    - name: web-admin-port
      port: 9090
      targetPort: 9090
