apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: yorkie
  labels:
    app: etcd
spec:
  clusterIP: None
  selector:
    app: etcd
  ports:
    - name: etcd-port
      port: 2379
      targetPort: 2379
    - name: etcd-second-port
      port: 2380
      targetPort: 2380
