version: '3.3'

services:
  envoy:
    build:
      context: ./
      dockerfile: ./envoy.Dockerfile
    image: 'grpcweb:envoy'
    container_name: 'envoy'
    restart: always
    ports:
      - '8090:8090'
      - '9090:9090'
      - '9901:9901'
    command: ['/etc/envoy/envoy.yaml']
    depends_on:
      - yorkie
    # If you're using Mac or Windows, this special domain name("host.docker.internal" which makes containers able to connect to the host)
    # is supported by default.
    # But if you're using Linux and want an envoy container to communicate with the host,
    # it may help to define "hst.docker.internal" in extra_hosts.
    # (Actually, other hostnames are available, but in that case you should update clusters[].host configurations of envoy.yaml)
    extra_hosts:
      - "host.docker.internal:host-gateway"
  yorkie:
    image: 'yorkieteam/yorkie:latest'
    container_name: 'yorkie'
    command: [
      'server',
      '--mongo-connection-uri',
      'mongodb://mongo:27017',
      '--enable-pprof',
    ]
    restart: always
    ports:
      - '11101:11101'
      - '11102:11102'
      - '11103:11103'
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - '9090:9090'
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - '2379:2379'
      - '2380:2380'
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
