apiVersion: apps/v1
kind: Deployment
metadata:
  name: yorkie-server-deployment
  namespace: yorkie
  labels:
    app: yorkie-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yorkie-server
  template:
    metadata:
      labels:
        app: yorkie-server
    spec:
      containers:
        - name: yorkie
          # env will be configured in later updates
          # (including secrets for certain variables)
          args:
            - server
            - --mongo-connection-uri
            - mongodb://mongo-service:27017
            - --etcd-endpoints
            - http://etcd-service:2379
            - --enable-pprof
          image: yorkieteam/yorkie:latest
          ports:
            - containerPort: 11101
            - containerPort: 11102
            - containerPort: 11103
          # resources will be configured in later updates
          # (need to load test to configure resource capacity)
          resources: {}
