apiVersion: v1
kind: Service
metadata:
  name: protetheus-service
  labels:
    app: protetheus
spec:
  type: NodePort
  selector:
    app: protetheus
  ports:
    - name: metric-port
      port: 9090
      targetPort: 9090
