apiVersion: v1
kind: Service
metadata:
  name: yorkie-protetheus-service
  namespace: yorkie
  labels:
    app: yorkie-protetheus
spec:
  type: NodePort
  selector:
    app: yorkie-protetheus
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
