apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  namespace: yorkie
  labels:
    app: mongo-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
