apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
  namespace: yorkie
  labels:
    app: prometheus-claim
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
