apiVersion: apps/v1
kind: Deployment
metadata:
  name: yorkie-etcd-deployment
  namespace: yorkie
  labels:
    app: yorkie-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yorkie-etcd
  template:
    metadata:
      labels:
        app: yorkie-etcd
    spec:
      containers:
        - env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: http://etcd:2379
          image: bitnami/etcd:latest
          name: etcd
          ports:
            - containerPort: 2379
            - containerPort: 2380
      restartPolicy: Always
