apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-statefulset
  labels:
    app: prometheus
spec:
  replicas: 1
  serviceName: prometheus
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus/
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-persistent-storage
              mountPath: /etc/prometheus/
            - name: prometheus-config
              mountPath: /prometheus/
          resources: {}
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-configmap
  volumeClaimTemplates:
    - metadata:
        name: prometheus-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 400Mi
