apiVersion: apps/v1
kind: Deployment
metadata:
  name: yorkie-prometheus-deployment
  namespace: yorkie
  labels:
    app: yorkie-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yorkie-prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yorkie-prometheus
    spec:
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus.yml
          image: prom/prometheus:latest
          name: prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-claim
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: prometheus-claim
          persistentVolumeClaim:
            claimName: prometheus-claim
            readOnly: true
