apiVersion: apps/v1
kind: Deployment
metadata:
  name: yorkie-server-deployment
  namespace: yorkie
  labels:
    app: yorkie-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yorkie-server
  template:
    metadata:
      labels:
        app: yorkie-server
    spec:
      containers:
        - args:
            - server
            - --mongo-connection-uri
            - mongodb://mongo:27017
            - --enable-pprof
          image: yorkieteam/yorkie:latest
          name: yorkie
          ports:
            - containerPort: 11101
            - containerPort: 11102
            - containerPort: 11103
